### ISSUE TITLE
PropertySortOrder not honoured

### ISSUE THREAD

**Issue by andykenward** [adamwalzer/vscode-scss-lint#1]
Doesn't honour the PropertySortOrder rule.

example rule
```
  PropertySortOrder:
    enabled: true
    order:
      - content
      - z-index
      - float
      - clear
```

**Comment by adamwalzer** [comment]
Please try

```
    PropertySortOrder:
        severity: error
        order:
            - content
            - z-index
            - float
            - clear
```

and let me know if that works. Thanks!
