### ISSUE TITLE
Package does not work in VS Code

### ISSUE THREAD

**Issue by chrisbutler** [adamwalzer/vscode-scss-lint#27]
Running `scss-lint` in terminal produces expected output/catches errors... but the plugin finds 0 errors

`.scss-lint.yml` file is in root directory:
```yml
linters:
  SelectorFormat:
    convention: hyphenated_BEM
  NestingDepth:
    enabled: true
    max_depth: 4
```
