### ISSUE TITLE
@supports at-rule displays linter error when nested inside media query

### ISSUE THREAD

**Issue by jeremyvii** [adamwalzer/vscode-scss-lint#28]
The following snippet causes a linter error(`{ expected`).
``` scss
@media (min-width: $bp) {
  @supports (position: sticky) {
    position: sticky;
  }
}
```

However, `@supports` and `@media` work fine independently. My guess is it has something to do with CSS property in `@supports` confusing the linter.

When linting without vscode in `scss-lint` I experience no error.
